version: '3.9'

services:
  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    command: "listen --events ${EVENTS} --forward-to ${API_ENDPOINT}"
    env_file:
      - .env
